-- =====================================================================
-- drainIQ demo/test data (5 devices, alarm rules, ~3 days of hourly
-- measurements, and a mix of triggered/acknowledged/resolved alarms).
-- Generated by dumping the data seeded by drainIQ/Data/Seed/DbSeeder.cs
-- locally (pg_dump --data-only --inserts). Apply AFTER migrations
-- (`dotnet ef database update`) on an otherwise-empty database.
--
-- Demo login: test@drainiq.hr / Test123!@#
--
-- Usage: psql -h localhost -U <user> -d drainiq -f demo_data.sql
-- =====================================================================

BEGIN;

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Homebrew)
-- Dumped by pg_dump version 16.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: riverdeer
--

INSERT INTO public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('01a08cdc-547a-786a-946f-4b1fb6facdbc', 'test@drainiq.hr', 'TEST@DRAINIQ.HR', 'test@drainiq.hr', 'TEST@DRAINIQ.HR', false, 'AQAAAAIAAYagAAAAENWNWuhlrovVZz0sKsuS09Mmpy0TTORSXRAgKBrdUP71RPXMdiLeQIypBkuKdSGzlg==', 'L7YZ3E5JKCZ4X76NKXSFXYGILLJSI4UQ', '39ba68ff-ec19-43b2-9f8b-0e445ae847fc', NULL, false, false, NULL, true, 0);


--
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: riverdeer
--

INSERT INTO public.devices (device_id, device_name, lat, long, description, is_active, created_at, updated_at) VALUES (1, 'Korzo', 45.327100, 14.442200, 'Manhole sensor - Korzo, gradski centar', true, '2026-09-10 21:47:25.017855+02', '2026-09-10 21:47:25.017855+02');
INSERT INTO public.devices (device_id, device_name, lat, long, description, is_active, created_at, updated_at) VALUES (2, 'Riva - Ponte Rosso', 45.325500, 14.440700, 'Manhole sensor - luka, blizina mora', true, '2026-09-10 21:47:25.017855+02', '2026-09-10 21:47:25.017855+02');
INSERT INTO public.devices (device_id, device_name, lat, long, description, is_active, created_at, updated_at) VALUES (3, 'Mlaka', 45.322200, 14.424100, 'Manhole sensor - Mlaka', true, '2026-09-10 21:47:25.017855+02', '2026-09-10 21:47:25.017855+02');
INSERT INTO public.devices (device_id, device_name, lat, long, description, is_active, created_at, updated_at) VALUES (4, 'Podmurvice', 45.331500, 14.461400, 'Manhole sensor - Podmurvice', true, '2026-09-10 21:47:25.017855+02', '2026-09-10 21:47:25.017855+02');
INSERT INTO public.devices (device_id, device_name, lat, long, description, is_active, created_at, updated_at) VALUES (5, 'Škurinje', 45.317200, 14.476300, 'Manhole sensor - Škurinje', true, '2026-09-10 21:47:25.017855+02', '2026-09-10 21:47:25.017855+02');


--
-- Data for Name: alarm_rules; Type: TABLE DATA; Schema: public; Owner: riverdeer
--

INSERT INTO public.alarm_rules (rule_id, device_id, alarm_name, alarm_type, threshold_value, comparator, is_active, created_at, updated_at) VALUES (1, 1, 'Visoka razina vode', 'water_level', 15.00, '<=', true, '2026-09-10 21:47:25.057933+02', '2026-09-10 21:47:25.057933+02');
INSERT INTO public.alarm_rules (rule_id, device_id, alarm_name, alarm_type, threshold_value, comparator, is_active, created_at, updated_at) VALUES (2, 2, 'Visoka razina vode', 'water_level', 15.00, '<=', true, '2026-09-10 21:47:25.057933+02', '2026-09-10 21:47:25.057933+02');
INSERT INTO public.alarm_rules (rule_id, device_id, alarm_name, alarm_type, threshold_value, comparator, is_active, created_at, updated_at) VALUES (3, 3, 'Visoka razina vode', 'water_level', 15.00, '<=', true, '2026-09-10 21:47:25.057933+02', '2026-09-10 21:47:25.057933+02');
INSERT INTO public.alarm_rules (rule_id, device_id, alarm_name, alarm_type, threshold_value, comparator, is_active, created_at, updated_at) VALUES (4, 4, 'Visoka razina vode', 'water_level', 15.00, '<=', true, '2026-09-10 21:47:25.057933+02', '2026-09-10 21:47:25.057933+02');
INSERT INTO public.alarm_rules (rule_id, device_id, alarm_name, alarm_type, threshold_value, comparator, is_active, created_at, updated_at) VALUES (5, 5, 'Visoka razina vode', 'water_level', 15.00, '<=', true, '2026-09-10 21:47:25.057933+02', '2026-09-10 21:47:25.057933+02');


--
-- Data for Name: measurements; Type: TABLE DATA; Schema: public; Owner: riverdeer
--

INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (1, 1, 44.00, '2026-09-07 21:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (2, 1, 44.00, '2026-09-07 22:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (3, 1, 48.00, '2026-09-07 23:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (4, 1, 44.00, '2026-09-08 00:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (5, 1, 45.00, '2026-09-08 01:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (6, 1, 50.00, '2026-09-08 02:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (7, 1, 48.00, '2026-09-08 03:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (8, 1, 44.00, '2026-09-08 04:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (9, 1, 51.00, '2026-09-08 05:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (10, 1, 45.00, '2026-09-08 06:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (11, 1, 45.00, '2026-09-08 07:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (12, 1, 48.00, '2026-09-08 08:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (13, 1, 46.00, '2026-09-08 09:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (14, 1, 47.00, '2026-09-08 10:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (15, 1, 45.00, '2026-09-08 11:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (16, 1, 48.00, '2026-09-08 12:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (17, 1, 43.00, '2026-09-08 13:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (18, 1, 51.00, '2026-09-08 14:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (19, 1, 49.00, '2026-09-08 15:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (20, 1, 47.00, '2026-09-08 16:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (21, 1, 6.00, '2026-09-08 17:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (22, 1, 6.00, '2026-09-08 18:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (23, 1, 10.00, '2026-09-08 19:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (24, 1, 10.00, '2026-09-08 20:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (25, 1, 48.00, '2026-09-08 21:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (26, 1, 43.00, '2026-09-08 22:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (27, 1, 50.00, '2026-09-08 23:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (28, 1, 44.00, '2026-09-09 00:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (29, 1, 52.00, '2026-09-09 01:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (30, 1, 50.00, '2026-09-09 02:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (31, 1, 48.00, '2026-09-09 03:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (32, 1, 45.00, '2026-09-09 04:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (33, 1, 43.00, '2026-09-09 05:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (34, 1, 46.00, '2026-09-09 06:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (35, 1, 49.00, '2026-09-09 07:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (36, 1, 52.00, '2026-09-09 08:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (37, 1, 43.00, '2026-09-09 09:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (38, 1, 48.00, '2026-09-09 10:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (39, 1, 51.00, '2026-09-09 11:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (40, 1, 51.00, '2026-09-09 12:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (41, 1, 47.00, '2026-09-09 13:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (42, 1, 44.00, '2026-09-09 14:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (43, 1, 43.00, '2026-09-09 15:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (44, 1, 43.00, '2026-09-09 16:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (45, 1, 51.00, '2026-09-09 17:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (46, 1, 49.00, '2026-09-09 18:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (47, 1, 44.00, '2026-09-09 19:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (48, 1, 45.00, '2026-09-09 20:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (49, 1, 51.00, '2026-09-09 21:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (50, 1, 46.00, '2026-09-09 22:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (51, 1, 50.00, '2026-09-09 23:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (52, 1, 44.00, '2026-09-10 00:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (53, 1, 43.00, '2026-09-10 01:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (54, 1, 49.00, '2026-09-10 02:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (55, 1, 48.00, '2026-09-10 03:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (56, 1, 43.00, '2026-09-10 04:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (57, 1, 47.00, '2026-09-10 05:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (58, 1, 50.00, '2026-09-10 06:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (59, 1, 49.00, '2026-09-10 07:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (60, 1, 45.00, '2026-09-10 08:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (61, 1, 43.00, '2026-09-10 09:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (62, 1, 47.00, '2026-09-10 10:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (63, 1, 45.00, '2026-09-10 11:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (64, 1, 43.00, '2026-09-10 12:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (65, 1, 50.00, '2026-09-10 13:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (66, 1, 43.00, '2026-09-10 14:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (67, 1, 8.00, '2026-09-10 15:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (68, 1, 6.00, '2026-09-10 16:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (69, 1, 10.00, '2026-09-10 17:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (70, 1, 47.00, '2026-09-10 18:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (71, 1, 48.00, '2026-09-10 19:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (72, 1, 48.00, '2026-09-10 20:47:25.073526+02', '2026-09-10 21:47:25.090466+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (73, 2, 39.00, '2026-09-07 21:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (74, 2, 30.00, '2026-09-07 22:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (75, 2, 30.00, '2026-09-07 23:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (76, 2, 30.00, '2026-09-08 00:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (77, 2, 37.00, '2026-09-08 01:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (78, 2, 30.00, '2026-09-08 02:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (79, 2, 40.00, '2026-09-08 03:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (80, 2, 40.00, '2026-09-08 04:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (81, 2, 35.00, '2026-09-08 05:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (82, 2, 34.00, '2026-09-08 06:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (83, 2, 36.00, '2026-09-08 07:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (84, 2, 30.00, '2026-09-08 08:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (85, 2, 34.00, '2026-09-08 09:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (86, 2, 31.00, '2026-09-08 10:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (87, 2, 34.00, '2026-09-08 11:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (88, 2, 38.00, '2026-09-08 12:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (89, 2, 35.00, '2026-09-08 13:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (90, 2, 34.00, '2026-09-08 14:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (91, 2, 33.00, '2026-09-08 15:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (92, 2, 39.00, '2026-09-08 16:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (93, 2, 9.00, '2026-09-08 17:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (94, 2, 10.00, '2026-09-08 18:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (95, 2, 6.00, '2026-09-08 19:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (96, 2, 11.00, '2026-09-08 20:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (97, 2, 40.00, '2026-09-08 21:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (98, 2, 33.00, '2026-09-08 22:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (99, 2, 37.00, '2026-09-08 23:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (100, 2, 31.00, '2026-09-09 00:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (101, 2, 31.00, '2026-09-09 01:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (102, 2, 34.00, '2026-09-09 02:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (103, 2, 33.00, '2026-09-09 03:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (104, 2, 38.00, '2026-09-09 04:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (105, 2, 31.00, '2026-09-09 05:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (106, 2, 31.00, '2026-09-09 06:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (107, 2, 32.00, '2026-09-09 07:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (108, 2, 36.00, '2026-09-09 08:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (109, 2, 35.00, '2026-09-09 09:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (110, 2, 40.00, '2026-09-09 10:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (111, 2, 38.00, '2026-09-09 11:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (112, 2, 37.00, '2026-09-09 12:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (113, 2, 37.00, '2026-09-09 13:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (114, 2, 33.00, '2026-09-09 14:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (115, 2, 36.00, '2026-09-09 15:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (116, 2, 40.00, '2026-09-09 16:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (117, 2, 37.00, '2026-09-09 17:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (118, 2, 30.00, '2026-09-09 18:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (119, 2, 33.00, '2026-09-09 19:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (120, 2, 40.00, '2026-09-09 20:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (121, 2, 30.00, '2026-09-09 21:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (122, 2, 32.00, '2026-09-09 22:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (123, 2, 32.00, '2026-09-09 23:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (124, 2, 30.00, '2026-09-10 00:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (125, 2, 32.00, '2026-09-10 01:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (126, 2, 36.00, '2026-09-10 02:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (127, 2, 34.00, '2026-09-10 03:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (128, 2, 31.00, '2026-09-10 04:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (129, 2, 40.00, '2026-09-10 05:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (130, 2, 31.00, '2026-09-10 06:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (131, 2, 31.00, '2026-09-10 07:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (132, 2, 33.00, '2026-09-10 08:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (133, 2, 33.00, '2026-09-10 09:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (134, 2, 38.00, '2026-09-10 10:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (135, 2, 39.00, '2026-09-10 11:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (136, 2, 30.00, '2026-09-10 12:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (137, 2, 30.00, '2026-09-10 13:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (138, 2, 39.00, '2026-09-10 14:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (139, 2, 11.00, '2026-09-10 15:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (140, 2, 7.00, '2026-09-10 16:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (141, 2, 11.00, '2026-09-10 17:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (142, 2, 39.00, '2026-09-10 18:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (143, 2, 33.00, '2026-09-10 19:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (144, 2, 35.00, '2026-09-10 20:47:25.073526+02', '2026-09-10 21:47:25.183698+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (145, 3, 48.00, '2026-09-07 21:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (146, 3, 44.00, '2026-09-07 22:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (147, 3, 45.00, '2026-09-07 23:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (148, 3, 44.00, '2026-09-08 00:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (149, 3, 42.00, '2026-09-08 01:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (150, 3, 44.00, '2026-09-08 02:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (151, 3, 52.00, '2026-09-08 03:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (152, 3, 52.00, '2026-09-08 04:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (153, 3, 50.00, '2026-09-08 05:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (154, 3, 43.00, '2026-09-08 06:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (155, 3, 51.00, '2026-09-08 07:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (156, 3, 44.00, '2026-09-08 08:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (157, 3, 45.00, '2026-09-08 09:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (158, 3, 48.00, '2026-09-08 10:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (159, 3, 48.00, '2026-09-08 11:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (160, 3, 49.00, '2026-09-08 12:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (161, 3, 43.00, '2026-09-08 13:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (162, 3, 48.00, '2026-09-08 14:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (163, 3, 46.00, '2026-09-08 15:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (164, 3, 51.00, '2026-09-08 16:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (165, 3, 8.00, '2026-09-08 17:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (166, 3, 8.00, '2026-09-08 18:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (167, 3, 11.00, '2026-09-08 19:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (168, 3, 8.00, '2026-09-08 20:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (169, 3, 47.00, '2026-09-08 21:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (170, 3, 52.00, '2026-09-08 22:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (171, 3, 50.00, '2026-09-08 23:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (172, 3, 43.00, '2026-09-09 00:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (173, 3, 43.00, '2026-09-09 01:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (174, 3, 42.00, '2026-09-09 02:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (175, 3, 44.00, '2026-09-09 03:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (176, 3, 52.00, '2026-09-09 04:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (177, 3, 49.00, '2026-09-09 05:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (178, 3, 46.00, '2026-09-09 06:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (179, 3, 48.00, '2026-09-09 07:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (180, 3, 46.00, '2026-09-09 08:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (181, 3, 43.00, '2026-09-09 09:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (182, 3, 52.00, '2026-09-09 10:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (183, 3, 52.00, '2026-09-09 11:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (184, 3, 51.00, '2026-09-09 12:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (185, 3, 43.00, '2026-09-09 13:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (186, 3, 45.00, '2026-09-09 14:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (187, 3, 47.00, '2026-09-09 15:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (188, 3, 48.00, '2026-09-09 16:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (189, 3, 52.00, '2026-09-09 17:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (190, 3, 51.00, '2026-09-09 18:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (191, 3, 50.00, '2026-09-09 19:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (192, 3, 45.00, '2026-09-09 20:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (193, 3, 45.00, '2026-09-09 21:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (194, 3, 47.00, '2026-09-09 22:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (195, 3, 50.00, '2026-09-09 23:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (196, 3, 44.00, '2026-09-10 00:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (197, 3, 51.00, '2026-09-10 01:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (198, 3, 49.00, '2026-09-10 02:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (199, 3, 44.00, '2026-09-10 03:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (200, 3, 45.00, '2026-09-10 04:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (201, 3, 44.00, '2026-09-10 05:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (202, 3, 51.00, '2026-09-10 06:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (203, 3, 49.00, '2026-09-10 07:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (204, 3, 42.00, '2026-09-10 08:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (205, 3, 46.00, '2026-09-10 09:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (206, 3, 50.00, '2026-09-10 10:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (207, 3, 51.00, '2026-09-10 11:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (208, 3, 50.00, '2026-09-10 12:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (209, 3, 52.00, '2026-09-10 13:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (210, 3, 52.00, '2026-09-10 14:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (211, 3, 8.00, '2026-09-10 15:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (212, 3, 11.00, '2026-09-10 16:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (213, 3, 11.00, '2026-09-10 17:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (214, 3, 43.00, '2026-09-10 18:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (215, 3, 48.00, '2026-09-10 19:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (216, 3, 44.00, '2026-09-10 20:47:25.073526+02', '2026-09-10 21:47:25.226256+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (217, 4, 47.00, '2026-09-07 21:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (218, 4, 49.00, '2026-09-07 22:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (219, 4, 43.00, '2026-09-07 23:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (220, 4, 50.00, '2026-09-08 00:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (221, 4, 45.00, '2026-09-08 01:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (222, 4, 47.00, '2026-09-08 02:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (223, 4, 49.00, '2026-09-08 03:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (224, 4, 44.00, '2026-09-08 04:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (225, 4, 47.00, '2026-09-08 05:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (226, 4, 50.00, '2026-09-08 06:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (227, 4, 48.00, '2026-09-08 07:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (228, 4, 44.00, '2026-09-08 08:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (229, 4, 52.00, '2026-09-08 09:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (230, 4, 42.00, '2026-09-08 10:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (231, 4, 42.00, '2026-09-08 11:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (232, 4, 44.00, '2026-09-08 12:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (233, 4, 45.00, '2026-09-08 13:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (234, 4, 43.00, '2026-09-08 14:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (235, 4, 45.00, '2026-09-08 15:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (236, 4, 44.00, '2026-09-08 16:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (237, 4, 11.00, '2026-09-08 17:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (238, 4, 8.00, '2026-09-08 18:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (239, 4, 8.00, '2026-09-08 19:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (240, 4, 8.00, '2026-09-08 20:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (241, 4, 50.00, '2026-09-08 21:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (242, 4, 49.00, '2026-09-08 22:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (243, 4, 52.00, '2026-09-08 23:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (244, 4, 45.00, '2026-09-09 00:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (245, 4, 51.00, '2026-09-09 01:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (246, 4, 45.00, '2026-09-09 02:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (247, 4, 44.00, '2026-09-09 03:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (248, 4, 52.00, '2026-09-09 04:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (249, 4, 48.00, '2026-09-09 05:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (250, 4, 48.00, '2026-09-09 06:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (251, 4, 46.00, '2026-09-09 07:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (252, 4, 52.00, '2026-09-09 08:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (253, 4, 42.00, '2026-09-09 09:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (254, 4, 47.00, '2026-09-09 10:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (255, 4, 51.00, '2026-09-09 11:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (256, 4, 45.00, '2026-09-09 12:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (257, 4, 52.00, '2026-09-09 13:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (258, 4, 51.00, '2026-09-09 14:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (259, 4, 51.00, '2026-09-09 15:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (260, 4, 42.00, '2026-09-09 16:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (261, 4, 45.00, '2026-09-09 17:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (262, 4, 48.00, '2026-09-09 18:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (263, 4, 42.00, '2026-09-09 19:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (264, 4, 51.00, '2026-09-09 20:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (265, 4, 46.00, '2026-09-09 21:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (266, 4, 49.00, '2026-09-09 22:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (267, 4, 49.00, '2026-09-09 23:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (268, 4, 52.00, '2026-09-10 00:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (269, 4, 45.00, '2026-09-10 01:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (270, 4, 52.00, '2026-09-10 02:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (271, 4, 50.00, '2026-09-10 03:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (272, 4, 42.00, '2026-09-10 04:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (273, 4, 45.00, '2026-09-10 05:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (274, 4, 49.00, '2026-09-10 06:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (275, 4, 42.00, '2026-09-10 07:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (276, 4, 49.00, '2026-09-10 08:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (277, 4, 47.00, '2026-09-10 09:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (278, 4, 46.00, '2026-09-10 10:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (279, 4, 45.00, '2026-09-10 11:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (280, 4, 44.00, '2026-09-10 12:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (281, 4, 48.00, '2026-09-10 13:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (282, 4, 49.00, '2026-09-10 14:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (283, 4, 9.00, '2026-09-10 15:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (284, 4, 7.00, '2026-09-10 16:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (285, 4, 9.00, '2026-09-10 17:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (286, 4, 43.00, '2026-09-10 18:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (287, 4, 43.00, '2026-09-10 19:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (288, 4, 51.00, '2026-09-10 20:47:25.073526+02', '2026-09-10 21:47:25.26779+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (289, 5, 45.00, '2026-09-07 21:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (290, 5, 38.00, '2026-09-07 22:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (291, 5, 35.00, '2026-09-07 23:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (292, 5, 41.00, '2026-09-08 00:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (293, 5, 38.00, '2026-09-08 01:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (294, 5, 36.00, '2026-09-08 02:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (295, 5, 37.00, '2026-09-08 03:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (296, 5, 42.00, '2026-09-08 04:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (297, 5, 36.00, '2026-09-08 05:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (298, 5, 45.00, '2026-09-08 06:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (299, 5, 36.00, '2026-09-08 07:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (300, 5, 42.00, '2026-09-08 08:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (301, 5, 37.00, '2026-09-08 09:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (302, 5, 42.00, '2026-09-08 10:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (303, 5, 42.00, '2026-09-08 11:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (304, 5, 44.00, '2026-09-08 12:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (305, 5, 38.00, '2026-09-08 13:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (306, 5, 41.00, '2026-09-08 14:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (307, 5, 39.00, '2026-09-08 15:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (308, 5, 39.00, '2026-09-08 16:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (309, 5, 7.00, '2026-09-08 17:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (310, 5, 10.00, '2026-09-08 18:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (311, 5, 9.00, '2026-09-08 19:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (312, 5, 9.00, '2026-09-08 20:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (313, 5, 42.00, '2026-09-08 21:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (314, 5, 39.00, '2026-09-08 22:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (315, 5, 42.00, '2026-09-08 23:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (316, 5, 45.00, '2026-09-09 00:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (317, 5, 42.00, '2026-09-09 01:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (318, 5, 37.00, '2026-09-09 02:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (319, 5, 38.00, '2026-09-09 03:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (320, 5, 40.00, '2026-09-09 04:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (321, 5, 43.00, '2026-09-09 05:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (322, 5, 42.00, '2026-09-09 06:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (323, 5, 38.00, '2026-09-09 07:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (324, 5, 41.00, '2026-09-09 08:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (325, 5, 43.00, '2026-09-09 09:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (326, 5, 39.00, '2026-09-09 10:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (327, 5, 45.00, '2026-09-09 11:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (328, 5, 40.00, '2026-09-09 12:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (329, 5, 44.00, '2026-09-09 13:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (330, 5, 35.00, '2026-09-09 14:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (331, 5, 39.00, '2026-09-09 15:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (332, 5, 39.00, '2026-09-09 16:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (333, 5, 36.00, '2026-09-09 17:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (334, 5, 41.00, '2026-09-09 18:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (335, 5, 39.00, '2026-09-09 19:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (336, 5, 35.00, '2026-09-09 20:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (337, 5, 45.00, '2026-09-09 21:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (338, 5, 40.00, '2026-09-09 22:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (339, 5, 38.00, '2026-09-09 23:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (340, 5, 40.00, '2026-09-10 00:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (341, 5, 42.00, '2026-09-10 01:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (342, 5, 39.00, '2026-09-10 02:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (343, 5, 36.00, '2026-09-10 03:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (344, 5, 37.00, '2026-09-10 04:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (345, 5, 43.00, '2026-09-10 05:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (346, 5, 40.00, '2026-09-10 06:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (347, 5, 44.00, '2026-09-10 07:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (348, 5, 45.00, '2026-09-10 08:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (349, 5, 40.00, '2026-09-10 09:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (350, 5, 37.00, '2026-09-10 10:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (351, 5, 45.00, '2026-09-10 11:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (352, 5, 44.00, '2026-09-10 12:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (353, 5, 41.00, '2026-09-10 13:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (354, 5, 42.00, '2026-09-10 14:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (355, 5, 11.00, '2026-09-10 15:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (356, 5, 9.00, '2026-09-10 16:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (357, 5, 7.00, '2026-09-10 17:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (358, 5, 35.00, '2026-09-10 18:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (359, 5, 36.00, '2026-09-10 19:47:25.073526+02', '2026-09-10 21:47:25.343413+02');
INSERT INTO public.measurements (measurement_id, device_id, water_level_from_top_cm, sent_at, created_at) VALUES (360, 5, 44.00, '2026-09-10 20:47:25.073526+02', '2026-09-10 21:47:25.343413+02');


--
-- Data for Name: alarm_instances; Type: TABLE DATA; Schema: public; Owner: riverdeer
--

INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (5, 1, 67, '2026-09-10 21:47:25.158274+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (6, 1, 68, '2026-09-10 21:47:25.15967+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (7, 1, 69, '2026-09-10 21:47:25.16097+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (1, 1, 21, '2026-09-10 21:47:25.137511+02', 'acknowledged', '2026-09-10 22:02:25.137511+02', NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (2, 1, 22, '2026-09-10 21:47:25.142371+02', 'resolved', '2026-09-10 22:02:25.142371+02', '2026-09-10 22:27:25.142371+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (3, 1, 23, '2026-09-10 21:47:25.143844+02', 'resolved', '2026-09-10 22:02:25.143844+02', '2026-09-10 22:27:25.143844+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (4, 1, 24, '2026-09-10 21:47:25.145143+02', 'resolved', '2026-09-10 22:02:25.145143+02', '2026-09-10 22:27:25.145143+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (12, 2, 139, '2026-09-10 21:47:25.21614+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (13, 2, 140, '2026-09-10 21:47:25.217825+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (14, 2, 141, '2026-09-10 21:47:25.219517+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (8, 2, 93, '2026-09-10 21:47:25.194139+02', 'acknowledged', '2026-09-10 22:02:25.194139+02', NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (9, 2, 94, '2026-09-10 21:47:25.195955+02', 'resolved', '2026-09-10 22:02:25.195955+02', '2026-09-10 22:27:25.195955+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (10, 2, 95, '2026-09-10 21:47:25.19843+02', 'resolved', '2026-09-10 22:02:25.19843+02', '2026-09-10 22:27:25.19843+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (11, 2, 96, '2026-09-10 21:47:25.200673+02', 'resolved', '2026-09-10 22:02:25.200673+02', '2026-09-10 22:27:25.200673+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (19, 3, 211, '2026-09-10 21:47:25.25607+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (20, 3, 212, '2026-09-10 21:47:25.258114+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (21, 3, 213, '2026-09-10 21:47:25.260081+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (15, 3, 165, '2026-09-10 21:47:25.236754+02', 'acknowledged', '2026-09-10 22:02:25.236754+02', NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (16, 3, 166, '2026-09-10 21:47:25.23869+02', 'resolved', '2026-09-10 22:02:25.23869+02', '2026-09-10 22:27:25.23869+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (17, 3, 167, '2026-09-10 21:47:25.240731+02', 'resolved', '2026-09-10 22:02:25.240731+02', '2026-09-10 22:27:25.240731+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (18, 3, 168, '2026-09-10 21:47:25.242653+02', 'resolved', '2026-09-10 22:02:25.242653+02', '2026-09-10 22:27:25.242653+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (26, 4, 283, '2026-09-10 21:47:25.322279+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (27, 4, 284, '2026-09-10 21:47:25.331745+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (28, 4, 285, '2026-09-10 21:47:25.33473+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (22, 4, 237, '2026-09-10 21:47:25.287916+02', 'acknowledged', '2026-09-10 22:02:25.287916+02', NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (23, 4, 238, '2026-09-10 21:47:25.290227+02', 'resolved', '2026-09-10 22:02:25.290227+02', '2026-09-10 22:27:25.290227+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (24, 4, 239, '2026-09-10 21:47:25.295913+02', 'resolved', '2026-09-10 22:02:25.295913+02', '2026-09-10 22:27:25.295913+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (25, 4, 240, '2026-09-10 21:47:25.304283+02', 'resolved', '2026-09-10 22:02:25.304283+02', '2026-09-10 22:27:25.304283+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (33, 5, 355, '2026-09-10 21:47:25.381471+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (34, 5, 356, '2026-09-10 21:47:25.384001+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (35, 5, 357, '2026-09-10 21:47:25.386326+02', 'triggered', NULL, NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (29, 5, 309, '2026-09-10 21:47:25.357543+02', 'acknowledged', '2026-09-10 22:02:25.357543+02', NULL);
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (30, 5, 310, '2026-09-10 21:47:25.359998+02', 'resolved', '2026-09-10 22:02:25.359998+02', '2026-09-10 22:27:25.359998+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (31, 5, 311, '2026-09-10 21:47:25.362933+02', 'resolved', '2026-09-10 22:02:25.362933+02', '2026-09-10 22:27:25.362933+02');
INSERT INTO public.alarm_instances (alarm_id, rule_id, measurement_id, triggered_at, status, acknowledged_at, resolved_at) VALUES (32, 5, 312, '2026-09-10 21:47:25.365478+02', 'resolved', '2026-09-10 22:02:25.365478+02', '2026-09-10 22:27:25.365478+02');


--
-- Data for Name: user_device; Type: TABLE DATA; Schema: public; Owner: riverdeer
--

INSERT INTO public.user_device (user_id, device_id, created_at) VALUES ('01a08cdc-547a-786a-946f-4b1fb6facdbc', 1, '2026-09-10 21:47:25.057933+02');
INSERT INTO public.user_device (user_id, device_id, created_at) VALUES ('01a08cdc-547a-786a-946f-4b1fb6facdbc', 2, '2026-09-10 21:47:25.057933+02');
INSERT INTO public.user_device (user_id, device_id, created_at) VALUES ('01a08cdc-547a-786a-946f-4b1fb6facdbc', 3, '2026-09-10 21:47:25.057933+02');
INSERT INTO public.user_device (user_id, device_id, created_at) VALUES ('01a08cdc-547a-786a-946f-4b1fb6facdbc', 4, '2026-09-10 21:47:25.057933+02');
INSERT INTO public.user_device (user_id, device_id, created_at) VALUES ('01a08cdc-547a-786a-946f-4b1fb6facdbc', 5, '2026-09-10 21:47:25.057933+02');


--
-- Name: alarm_instances_alarm_id_seq; Type: SEQUENCE SET; Schema: public; Owner: riverdeer
--

SELECT pg_catalog.setval('public.alarm_instances_alarm_id_seq', 35, true);


--
-- Name: alarm_rules_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: riverdeer
--

SELECT pg_catalog.setval('public.alarm_rules_rule_id_seq', 5, true);


--
-- Name: devices_device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: riverdeer
--

SELECT pg_catalog.setval('public.devices_device_id_seq', 5, true);


--
-- Name: measurements_measurement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: riverdeer
--

SELECT pg_catalog.setval('public.measurements_measurement_id_seq', 360, true);


--
-- PostgreSQL database dump complete
--

COMMIT;


